### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by vedxp** [Frontesque/Frontesque#1]
Hello sir, I need some help to implement `<NextSteps>` in my site which is using vuepress-theme-vt

I tried many ways, got errrors only.

Screenshot showing what I need help implementing in:

<details><summary>Show</summary>

![IMG_20220831_170656](https://user-images.githubusercontent.com/87353286/187669877-9332ec74-748a-4825-b4c8-f1f6e5e327b1.jpg)

</details>

#### Asking here cuz I couldn't find any other way to contact you!

**Comment by Frontesque** [comment]
the given information isn't useful without the error logs.

**Comment by vedxp** [comment]
> the given information isn't useful without the error logs.

Hmm, thanks for the reply.

I would better move to vuepress 2 or vitepress as some dependencies of vuepress-theme-vt are deprecated.

**Comment by VedxP** [comment]
![IMG_20220901_111013](https://user-images.githubusercontent.com/87353286/187839778-1d6c2903-5967-4005-aa03-df5008dfb14d.jpg)


## Please help resolving this error while trying to `npm init vue@3` or `npm init vue@2`
